INSERT INTO `empresa` (`idempresa`, `cif`, `ciudad`, `nombreempresa`, `nombreadmin`, `pais`, `provincia`, `telefono`) VALUES (1, 'B89321654', 'Mas', 'Pepito S.A.', 'Jose Lopez', 'Esp', 'Mad', 987654321);
INSERT INTO `empresa` (`idempresa`, `cif`, `ciudad`, `nombreempresa`, `nombreadmin`, `pais`, `provincia`, `telefono`) VALUES (3, 'shshs', 'hdhfdhd', 'sgyhwryhrws', 'dgywsyer', 'sfhdfhfd', 'dfhdhd', 1894523);
INSERT INTO `empresa` (`idempresa`, `cif`, `ciudad`, `nombreempresa`, `nombreadmin`, `pais`, `provincia`, `telefono`) VALUES (6, 'g5464646', 'Talaver', 'pitufo', 'pitufo cuchuflo', 'Esp', 'Toledo', 912165);
INSERT INTO `empresa` (`idempresa`, `cif`, `ciudad`, `nombreempresa`, `nombreadmin`, `pais`, `provincia`, `telefono`) VALUES (7, 'B987456', 'Madrid', 'Marcelo S.A.', 'Ministro Perlo', 'Esp', 'Madrid', 98562314);
INSERT INTO `empresa` (`idempresa`, `cif`, `ciudad`, `nombreempresa`, `nombreadmin`, `pais`, `provincia`, `telefono`) VALUES (8, 'B75632984', 'Mostoles', 'Pestinos S.A.', 'Alba Pernudo', 'Espania ', 'Madrid', 635214789);


INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (1, NULL, '12345', 'jose@pepito.com', 'Mas, Mad, Esp.', 'Pepito S.A.', b'1', '10-04-2023', 'Mas', 'Jose Lopez', 987654321, 1);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (2, NULL, 'raro', 'l@gmail.com', 'hdhfdhd, dfhdhd, sfhdfhfd.', 'sgyhwryhrws', b'1', '10-04-2023', 'hdhfdhd', 'dgywsyer', 1894523, 3);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (3, NULL, '741852', 'pitufo@pit.com', 'Talaver, Toledo, Esp.', 'pitufo', b'1', '10-04-2023', 'Talaver', 'pitufo cuchuflo', 912165, 6);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (4, NULL, '951632', 'min@marcelo.com', 'Madrid, Madrid, Esp.', 'Marcelo S.A.', b'1', '10-04-2023', 'Madrid', 'Macarron', 91234569, 7);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (5, NULL, '12345', 'marcelo@pestino.com', 'Mostoles, Madrid, Espania .', 'Pestinos S.A.', b'1', '11-04-2023', 'Fuenlabrada', 'Marcelo Pellegrini', 91234567, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (10, 'Gonzalez Irujo', '987', 'esteban@pestino.com', 'Calle Velazquez, Getafe', 'Pestinos S.A.', b'0', '09-05-1990', 'Madrid', 'Esteban', 915632487, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (11, 'Marquez Herrera', '987', 'fitipaldi@pestino.com', 'Calle Velazquez, Getafe', 'Pestinos S.A.', b'0', '09-05-1990', 'Madrid', 'Fitipaldi', 915632487, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (12, 'Perez Calar', '987', 'borja@pestino.com', 'Calle Velazquez, Getafe', 'Pestinos S.A.', b'0', '09-05-1990', 'Madrid', 'Borja', 915632487, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (13, 'Iglesias Sainz', '987', 'pablo@pestino.com', 'Calle Velazquez, Getafe', 'Pestinos S.A.', b'0', '09-05-1990', 'Madrid', 'Pablo', 915632487, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (17, 'Estopa Martinez', '987', 'felipe@pestino.com', 'Calle Velazquez, Getafe', 'Pestinos S.A.', b'0', '09-05-1990', 'Madrid', 'Felipe', 896532147, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (26, 'Tejero Lopez', '12345', 'fernando@pestino.com', 'Calle Pilluescas, Leganes', 'Pestinos S.A.', b'0', '03-06-1990', 'Madrid', 'Fernando', 848419849, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (28, 'Di Maria', '635', 'fideo@pestino.com', 'Rosario, Argentina', 'Pestinos S.A.', b'0', '05-10-2000', 'Madrid', 'Fideo', 161148151, 8);
INSERT INTO `usuario` (`idusuario`, `apellidosusuario`, `contrasena`, `correousuario`, `direccion`, `empresausuario`, `esadmin`, `fechanacimiento`, `lugartrabajo`, `nombreusuario`, `telefono`, `idempresa`) VALUES (29, 'Gonzalez Blanco', '123', 'raul@pestino.com', 'Pozuelo, Madrid', 'Pestinos S.A.', b'0', '01-05-1983', 'Madrid', 'Raul', 58941161, 8);


